### ISSUE TITLE
Uncaught TypeError: Class extends value undefined 

### ISSUE THREAD

**Issue by comountainclimber** [CityOfZion/wallet-connect-sdk#47]
Instantiating the `WcSdk` class like this: 

`const wcInstance = new WcSdk()`

Causes the following error below:

```
bootstrap:27 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Object../node_modules/@cityofzion/wallet-connect-sdk-core/node_modules/@walletconnect/client/dist/cjs/controllers/subscription.js (bundle.js:4240:36)
    at Object.options.factory (bundle.js:62140:31)
    at __webpack_require__ (bundle.js:61590:33)
    at fn (bundle.js:61811:21)
    at Object../node_modules/@cityofzion/wallet-connect-sdk-core/node_modules/@walletconnect/client/dist/cjs/controllers/pairing.js (bundle.js:3460:24)
    at Object.options.factory (bundle.js:62140:31)
    at __webpack_require__ (bundle.js:61590:33)
    at fn (bundle.js:61811:21)
    at Object../node_modules/@cityofzion/wallet-connect-sdk-core/node_modules/@walletconnect/client/dist/cjs/controllers/index.js (bundle.js:3426:22)
    at Object.options.factory (bundle.js:62140:31)
``` 
    
   After discussing with @melanke this is directly due to the use of yarn and can be resolved using yarn resolutions

**Comment by melanke** [comment]
We've created a workaround for this problem and it is solved on `beta` branch. Please, reopen the issue if you think it could be handled differently.
